name: ESP32 Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install Prerequisites
        shell: bash
        run: |
          npm install

          DISABLE_ESLINT_PLUGIN=true npm run build
          
          mkdir -p ./build/manifest
          
          curl https://github.com/${{github.repository}}/releases/download/firmware/esp32aif-plane-merged.bin > ./build/manifest/plane.bin
          echo '{ "name": "aif-copter", "builds": [{ "chipFamily": "ESP32", "parts": [{ "path": "https://${{github.repository_owner}}.github.io/aifwing/manifest/plane.bin", "offset": 0 }] }] }' > ./build/manifest/plane.json
          
          curl https://github.com/${{github.repository}}/releases/download/firmware/esp32aif-copter-merged.bin > ./build/manifest/copter.bin
          echo '{ "name": "aif-copter", "builds": [{ "chipFamily": "ESP32", "parts": [{ "path": "https://${{github.repository_owner}}.github.io/aifwing/manifest/copter.bin", "offset": 0 }] }] }' > ./build/manifest/copter.json

          npm run deploy
