name: ESP32 Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install Prerequisites
        shell: bash
        run: |
          npm install

          DISABLE_ESLINT_PLUGIN=true npm run build
          
          mkdir -p ./build/manifest
          
          wget https://github.com/${{github.repository}}/releases/download/firmware/esp32aif-plane-merged.bin -O ./build/manifest/plane.bin
          wget https://github.com/${{github.repository}}/releases/download/firmware/esp32aif-copter-merged.bin -O ./build/manifest/copter.bin

          file ./build/manifest/plane.bin
          file ./build/manifest/copter.bin
          
          echo '{ "name": "aif-copter", "builds": [{ "chipFamily": "ESP32", "parts": [{ "path": "https://${{github.repository_owner}}.github.io/aifwing/manifest/plane.bin", "offset": 0 }] }] }' > ./build/manifest/plane.json
          echo '{ "name": "aif-copter", "builds": [{ "chipFamily": "ESP32", "parts": [{ "path": "https://${{github.repository_owner}}.github.io/aifwing/manifest/copter.bin", "offset": 0 }] }] }' > ./build/manifest/copter.json

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.REPO_TOKEN }}
